// <auto-generated />
using System;
using BlogicCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogicCRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605135830_RozsireniTestovacichDat")]
    partial class RozsireniTestovacichDat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogicCRM.Models.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Advisors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 49,
                            BirthNumber = "750303/1111",
                            Email = "anna.kralova@firma.cz",
                            FirstName = "Anna",
                            LastName = "Králová",
                            Phone = "+420111222333"
                        },
                        new
                        {
                            Id = 2,
                            Age = 39,
                            BirthNumber = "850404/2222",
                            Email = "martin.dvorak@firma.cz",
                            FirstName = "Martin",
                            LastName = "Dvořák",
                            Phone = "+420444555666"
                        },
                        new
                        {
                            Id = 3,
                            Age = 41,
                            BirthNumber = "820505/3333",
                            Email = "lucie.novotna@firma.cz",
                            FirstName = "Lucie",
                            LastName = "Novotná",
                            Phone = "+420777888999"
                        },
                        new
                        {
                            Id = 4,
                            Age = 46,
                            BirthNumber = "800808/1212",
                            Email = "petr.svoboda@firma.cz",
                            FirstName = "Petr",
                            LastName = "Svoboda",
                            Phone = "+420201000111"
                        },
                        new
                        {
                            Id = 5,
                            Age = 41,
                            BirthNumber = "850909/2323",
                            Email = "hana.bartosova@firma.cz",
                            FirstName = "Hana",
                            LastName = "Bartošová",
                            Phone = "+420202000222"
                        },
                        new
                        {
                            Id = 6,
                            Age = 48,
                            BirthNumber = "780101/3434",
                            Email = "robert.masek@firma.cz",
                            FirstName = "Robert",
                            LastName = "Mašek",
                            Phone = "+420203000333"
                        },
                        new
                        {
                            Id = 7,
                            Age = 34,
                            BirthNumber = "920202/4545",
                            Email = "silvia.urban@firma.cz",
                            FirstName = "Silvia",
                            LastName = "Urban",
                            Phone = "+420204000444"
                        },
                        new
                        {
                            Id = 8,
                            Age = 31,
                            BirthNumber = "950303/5656",
                            Email = "ondrej.holub@firma.cz",
                            FirstName = "Ondřej",
                            LastName = "Holub",
                            Phone = "+420205000555"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 44,
                            BirthNumber = "800101/1234",
                            Email = "jan.novak@priklad.cz",
                            FirstName = "Jan",
                            LastName = "Novák",
                            Phone = "+420123456789"
                        },
                        new
                        {
                            Id = 2,
                            Age = 34,
                            BirthNumber = "900202/4321",
                            Email = "petra.svobodova@priklad.cz",
                            FirstName = "Petra",
                            LastName = "Svobodová",
                            Phone = "+420987654321"
                        },
                        new
                        {
                            Id = 3,
                            Age = 38,
                            BirthNumber = "880303/1111",
                            Email = "tomas.horak@priklad.cz",
                            FirstName = "Tomáš",
                            LastName = "Horák",
                            Phone = "+420601000001"
                        },
                        new
                        {
                            Id = 4,
                            Age = 35,
                            BirthNumber = "910404/2222",
                            Email = "katerina.mala@priklad.cz",
                            FirstName = "Kateřina",
                            LastName = "Malá",
                            Phone = "+420602000002"
                        },
                        new
                        {
                            Id = 5,
                            Age = 51,
                            BirthNumber = "750505/3333",
                            Email = "michal.benes@priklad.cz",
                            FirstName = "Michal",
                            LastName = "Beneš",
                            Phone = "+420603000003"
                        },
                        new
                        {
                            Id = 6,
                            Age = 27,
                            BirthNumber = "990606/4444",
                            Email = "jana.pokorna@priklad.cz",
                            FirstName = "Jana",
                            LastName = "Pokorná",
                            Phone = "+420604000004"
                        },
                        new
                        {
                            Id = 7,
                            Age = 61,
                            BirthNumber = "650707/5555",
                            Email = "pavel.cerny@priklad.cz",
                            FirstName = "Pavel",
                            LastName = "Černý",
                            Phone = "+420605000005"
                        },
                        new
                        {
                            Id = 8,
                            Age = 36,
                            BirthNumber = "900808/6666",
                            Email = "eva.kralikova@priklad.cz",
                            FirstName = "Eva",
                            LastName = "Králíková",
                            Phone = "+420606000006"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ManagerAdvisorId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ManagerAdvisorId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DateClosed = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnded = new DateTime(2027, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "ČSOB",
                            ManagerAdvisorId = 1,
                            RegistrationNumber = "C-2026-001"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            DateClosed = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnded = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "AEGON",
                            ManagerAdvisorId = 2,
                            RegistrationNumber = "C-2026-002"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            DateClosed = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "AXA",
                            ManagerAdvisorId = 3,
                            RegistrationNumber = "C-2026-003"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 3,
                            DateClosed = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Allianz",
                            ManagerAdvisorId = 4,
                            RegistrationNumber = "C-2026-004"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 4,
                            DateClosed = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnded = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Generali",
                            ManagerAdvisorId = 5,
                            RegistrationNumber = "C-2026-005"
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 5,
                            DateClosed = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Komerční banka",
                            ManagerAdvisorId = 6,
                            RegistrationNumber = "C-2026-006"
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 6,
                            DateClosed = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnded = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Česká spořitelna",
                            ManagerAdvisorId = 7,
                            RegistrationNumber = "C-2026-007"
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 7,
                            DateClosed = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "UniCredit",
                            ManagerAdvisorId = 8,
                            RegistrationNumber = "C-2026-008"
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 8,
                            DateClosed = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnded = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "AXA",
                            ManagerAdvisorId = 1,
                            RegistrationNumber = "C-2026-009"
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 1,
                            DateClosed = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnded = new DateTime(2027, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Kooperativa",
                            ManagerAdvisorId = 2,
                            RegistrationNumber = "C-2026-010"
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 2,
                            DateClosed = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "ČSOB",
                            ManagerAdvisorId = 3,
                            RegistrationNumber = "C-2026-011"
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 3,
                            DateClosed = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnded = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Generali",
                            ManagerAdvisorId = 4,
                            RegistrationNumber = "C-2026-012"
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 4,
                            DateClosed = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Allianz",
                            ManagerAdvisorId = 5,
                            RegistrationNumber = "C-2026-013"
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 5,
                            DateClosed = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnded = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "AEGON",
                            ManagerAdvisorId = 6,
                            RegistrationNumber = "C-2026-014"
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 6,
                            DateClosed = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateValidFrom = new DateTime(2026, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Komerční banka",
                            ManagerAdvisorId = 7,
                            RegistrationNumber = "C-2026-015"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.ContractAdvisor", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("int");

                    b.HasKey("ContractId", "AdvisorId");

                    b.HasIndex("AdvisorId");

                    b.ToTable("ContractAdvisors");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            AdvisorId = 1
                        },
                        new
                        {
                            ContractId = 1,
                            AdvisorId = 2
                        },
                        new
                        {
                            ContractId = 2,
                            AdvisorId = 2
                        },
                        new
                        {
                            ContractId = 3,
                            AdvisorId = 3
                        },
                        new
                        {
                            ContractId = 3,
                            AdvisorId = 1
                        },
                        new
                        {
                            ContractId = 4,
                            AdvisorId = 4
                        },
                        new
                        {
                            ContractId = 4,
                            AdvisorId = 1
                        },
                        new
                        {
                            ContractId = 5,
                            AdvisorId = 5
                        },
                        new
                        {
                            ContractId = 5,
                            AdvisorId = 2
                        },
                        new
                        {
                            ContractId = 5,
                            AdvisorId = 3
                        },
                        new
                        {
                            ContractId = 6,
                            AdvisorId = 6
                        },
                        new
                        {
                            ContractId = 7,
                            AdvisorId = 7
                        },
                        new
                        {
                            ContractId = 7,
                            AdvisorId = 4
                        },
                        new
                        {
                            ContractId = 8,
                            AdvisorId = 8
                        },
                        new
                        {
                            ContractId = 8,
                            AdvisorId = 5
                        },
                        new
                        {
                            ContractId = 8,
                            AdvisorId = 6
                        },
                        new
                        {
                            ContractId = 9,
                            AdvisorId = 1
                        },
                        new
                        {
                            ContractId = 9,
                            AdvisorId = 2
                        },
                        new
                        {
                            ContractId = 10,
                            AdvisorId = 2
                        },
                        new
                        {
                            ContractId = 10,
                            AdvisorId = 3
                        },
                        new
                        {
                            ContractId = 11,
                            AdvisorId = 3
                        },
                        new
                        {
                            ContractId = 11,
                            AdvisorId = 1
                        },
                        new
                        {
                            ContractId = 12,
                            AdvisorId = 4
                        },
                        new
                        {
                            ContractId = 13,
                            AdvisorId = 5
                        },
                        new
                        {
                            ContractId = 13,
                            AdvisorId = 2
                        },
                        new
                        {
                            ContractId = 14,
                            AdvisorId = 6
                        },
                        new
                        {
                            ContractId = 15,
                            AdvisorId = 7
                        },
                        new
                        {
                            ContractId = 15,
                            AdvisorId = 8
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.HasOne("BlogicCRM.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Advisor", "ManagerAdvisor")
                        .WithMany("ManagedContracts")
                        .HasForeignKey("ManagerAdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ManagerAdvisor");
                });

            modelBuilder.Entity("BlogicCRM.Models.ContractAdvisor", b =>
                {
                    b.HasOne("BlogicCRM.Models.Advisor", "Advisor")
                        .WithMany("ContractAdvisors")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Contract", "Contract")
                        .WithMany("ContractAdvisors")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BlogicCRM.Models.Advisor", b =>
                {
                    b.Navigation("ContractAdvisors");

                    b.Navigation("ManagedContracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.Navigation("ContractAdvisors");
                });
#pragma warning restore 612, 618
        }
    }
}
