// <auto-generated />
using System;
using BlogicCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogicCRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogicCRM.Models.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BirthNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Advisors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 49,
                            BirthNumber = "750303/1111",
                            Email = "anna.kralova@example.com",
                            FirstName = "Anna",
                            LastName = "Kralova",
                            Phone = "+420111222333"
                        },
                        new
                        {
                            Id = 2,
                            Age = 39,
                            BirthNumber = "850404/2222",
                            Email = "martin.dvorak@example.com",
                            FirstName = "Martin",
                            LastName = "Dvorak",
                            Phone = "+420444555666"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BirthNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 44,
                            BirthNumber = "800101/1234",
                            Email = "jan.novak@example.com",
                            FirstName = "Jan",
                            LastName = "Novák",
                            Phone = "+420123456789"
                        },
                        new
                        {
                            Id = 2,
                            Age = 34,
                            BirthNumber = "900202/4321",
                            Email = "petr.svoboda@example.com",
                            FirstName = "Petr",
                            LastName = "Svoboda",
                            Phone = "+420987654321"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ManagerAdvisorId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ManagerAdvisorId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DateClosed = new DateTime(2026, 5, 5, 10, 52, 0, 847, DateTimeKind.Utc).AddTicks(7612),
                            DateEnded = new DateTime(2027, 6, 4, 10, 52, 0, 847, DateTimeKind.Utc).AddTicks(7620),
                            DateValidFrom = new DateTime(2026, 5, 6, 10, 52, 0, 847, DateTimeKind.Utc).AddTicks(7619),
                            Institution = "Acme Corp",
                            ManagerAdvisorId = 1,
                            RegistrationNumber = "C-2026-001"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            DateClosed = new DateTime(2026, 5, 25, 10, 52, 0, 847, DateTimeKind.Utc).AddTicks(7649),
                            DateEnded = new DateTime(2026, 12, 4, 10, 52, 0, 847, DateTimeKind.Utc).AddTicks(7651),
                            DateValidFrom = new DateTime(2026, 5, 26, 10, 52, 0, 847, DateTimeKind.Utc).AddTicks(7650),
                            Institution = "Beta Ltd",
                            ManagerAdvisorId = 2,
                            RegistrationNumber = "C-2026-002"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.ContractAdvisor", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("int");

                    b.HasKey("ContractId", "AdvisorId");

                    b.HasIndex("AdvisorId");

                    b.ToTable("ContractAdvisors");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            AdvisorId = 1
                        },
                        new
                        {
                            ContractId = 1,
                            AdvisorId = 2
                        },
                        new
                        {
                            ContractId = 2,
                            AdvisorId = 2
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.HasOne("BlogicCRM.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Advisor", "ManagerAdvisor")
                        .WithMany("ManagedContracts")
                        .HasForeignKey("ManagerAdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ManagerAdvisor");
                });

            modelBuilder.Entity("BlogicCRM.Models.ContractAdvisor", b =>
                {
                    b.HasOne("BlogicCRM.Models.Advisor", "Advisor")
                        .WithMany("ContractAdvisors")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Contract", "Contract")
                        .WithMany("ContractAdvisors")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BlogicCRM.Models.Advisor", b =>
                {
                    b.Navigation("ContractAdvisors");

                    b.Navigation("ManagedContracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.Navigation("ContractAdvisors");
                });
#pragma warning restore 612, 618
        }
    }
}
